window.roots = {
    "fatih": "mektup",
    "mektubat": "şerbet",
    "teşekkür": "fikir",
    "müteşekkir": "teşebbüs",
    "teslim": "bereket",
    "makul": "emir",
    "tanzimat": "harab",
    "medrese": "rütbe",
    "meşrubat": "katib",
    "tekerrür": "nefes",
    "inkîlab": "zabıta",
    "mahsun": "zulüm",
    "kemal": "teslim",
    "müşrik": "dehşet",
    "meşhur": "cahil",
    "memur": "alim",
    "muzaffer": "kudüs",
    "muhabir": "hilafet",
    "mektup": "rahmet",
    "müneccim": "teftiş",
    "teşebbüs": "vekil",
    "selamet": "kerem"
}